export default [
  {
    _id: "123",
    tuit: "In 2021, our @NASAPersevere Mars rover landed",
    postedBy: { username: "NASA" },
    verified: true,
    handle: "NASA",
    time: "2h",
    logoImage: "images/nasa.jpg",
    avatarImage: "images/nasa.jpg",
    comments: 123,
    retuits: 234,
    likes: 345,
    dislikes: 345,
  },
  {
    _id: "234",
    tuit: "Ingenuity helicopter takes flight.",
    postedBy: { username: "NASA" },
    verified: true,
    handle: "NASA",
    time: "last month",
    logoImage: "images/nasa.jpg",
    avatarImage: "images/nasa.jpg",
    comments: 123,
    retuits: 234,
    likes: 10,
    dislikes: 10,
  },
];